theme: jekyll-theme-hacker
title: yoshiteru
description: work for a better future
google_analytics: UA-115471799-2

twitter:
  card: summary
  username: yoshiteru
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/yoshiteru_logo.png
        height: 576
        width: 576