twitter:
  username: yoshiteru
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/github_yoshiteru logo.png
        height: 640
        width: 1280

theme: jekyll-theme-hacker