theme: jekyll-theme-hacker
title: yoshiteru.work
description: For a better future
google_analytics: UA-115471799-2

twitter:
  card: summary_large_image
  username: yoshiteru
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/square.png
        height: 576
        width: 576