theme: jekyll-theme-hacker
title: yoshiteru.work
description: For a better future
google_analytics: UA-115471799-2

twitter:
  username: yoshiteru
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/yoshiteru_header.png
        height: 630
        width: 1200

image: /img/yoshiteru_header.png