theme: jekyll-theme-hacker
title: yoshiteru.work
description: For a better future
google_analytics: UA-115471799-2

twitter:
  card: summary
  username: yoshiteru
defaults:
  - scope:
      path: ""
    values:
    image: /img/yoshiteru_header.png
